### ISSUE TITLE
You like to live dangerously

### ISSUE THREAD

**Issue by immanuelfodor** [ayushgp/dotfiles#1]
Hi Ayush, just a friendly advice that you should never ever upload your command line history with cleartext login credentials :wink: 
E.g., https://github.com/ayushgp/dotfiles/blob/master/.zsh_history#L2487

**Comment by ayushgp** [comment]
Holy shit! Thanks man. I need to remove that ASAP.

**Comment by immanuelfodor** [comment]
You're welcome :) 
However, your commit history still has it:
https://github.com/ayushgp/dotfiles/commit/9ce1e94aca2d247ef7182c7e63e1ed2b6843e575
I think you should also [squash](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git) your history to make it disappear from spying eyes.
